In [1]:
import numpy as np

In [3]:
x = np.array([56,12,35,48,71,11,28])

In [4]:
print(x)

[56 12 35 48 71 11 28]


In [5]:

type(x)

numpy.ndarray

In [9]:
x.ndim

1

In [11]:
x

array([56, 12, 35, 48, 71, 11, 28])

In [13]:
x.dtype

dtype('int32')

In [15]:
a = 67865344444444444444447908098096783428947293847934798237293742937429384729387948

In [17]:
a

67865344444444444444447908098096783428947293847934798237293742937429384729387948

In [19]:
x

array([56, 12, 35, 48, 71, 11, 28])

In [21]:
x = np.array([56,12,35,48,71,11,28], dtype = np.int64)

In [23]:
x

array([56, 12, 35, 48, 71, 11, 28], dtype=int64)

In [25]:
x = np.array([56,12,35,48,71,11,28], dtype = np.int8)

In [27]:
x

array([56, 12, 35, 48, 71, 11, 28], dtype=int8)

In [29]:
x[0] = 78

In [31]:
x

array([78, 12, 35, 48, 71, 11, 28], dtype=int8)

In [33]:
x[2] = 99

In [35]:
x

array([78, 12, 99, 48, 71, 11, 28], dtype=int8)

In [37]:
x.size

7

In [39]:
x[9]=89

IndexError: index 9 is out of bounds for axis 0 with size 7

In [ ]:
x

In [42]:
x.shape

(7,)

In [44]:
x.min()

11

In [46]:
x.max()

99

In [48]:
x.mean()

49.57142857142857

In [50]:
x.std()

31.79783075645769

In [52]:
x.sum()

347

In [54]:
y = np.array([67, 89, 45.34, 69, 11, 35])

In [56]:
y

array([67.  , 89.  , 45.34, 69.  , 11.  , 35.  ])

In [58]:
y.dtype

dtype('float64')

In [60]:
z = np.array([67, 89, 45.34, 69, 11, True])

In [62]:
z

array([67.  , 89.  , 45.34, 69.  , 11.  ,  1.  ])

In [64]:
z = np.zeros(10, dtype = np.int16)

In [66]:
z

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [68]:
o = np.ones(10, dtype=np.int16)

In [70]:
o

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int16)

In [72]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [74]:
np.arange(4, 10)

array([4, 5, 6, 7, 8, 9])

In [76]:
np.arange(4,20, 3)

array([ 4,  7, 10, 13, 16, 19])

In [78]:
np.arange(20,1, -3)

array([20, 17, 14, 11,  8,  5,  2])

In [80]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [82]:
num1 = np.array([56,12,33,14,68,99])
num2 = np.array([28,28,19,39,38,74])

In [84]:
num1+10

array([ 66,  22,  43,  24,  78, 109])

In [86]:
num2 / 5

array([ 5.6,  5.6,  3.8,  7.8,  7.6, 14.8])

In [88]:
num1*4

array([224,  48, 132,  56, 272, 396])

In [90]:
[56,12,33,14,68,99]*3

[56, 12, 33, 14, 68, 99, 56, 12, 33, 14, 68, 99, 56, 12, 33, 14, 68, 99]

In [92]:
num1+num2

array([ 84,  40,  52,  53, 106, 173])

In [94]:
num1 - num2

array([ 28, -16,  14, -25,  30,  25])

## Matrix

In [97]:
M = np.array([[4,6,7],[1,2,3],[8,0,2],[9,3,5]])

In [99]:
M

array([[4, 6, 7],
       [1, 2, 3],
       [8, 0, 2],
       [9, 3, 5]])

In [101]:
M.dtype

dtype('int32')

In [103]:
M.shape

(4, 3)

In [105]:
M.size

12

In [107]:
M.ndim

2

In [109]:
M[2][1]

0

In [111]:
M

array([[4, 6, 7],
       [1, 2, 3],
       [8, 0, 2],
       [9, 3, 5]])

In [113]:
M[1:3, 0:2]   # slicing

array([[1, 2],
       [8, 0]])

In [115]:
M1 = M.resh

AttributeError: 'numpy.ndarray' object has no attribute 'resh'

In [122]:
M.reshape(3,4)

array([[4, 6, 7, 1],
       [2, 3, 8, 0],
       [2, 9, 3, 5]])

In [124]:
M.reshape

<function ndarray.reshape>

In [126]:
M.reshape(6,2)

array([[4, 6],
       [7, 1],
       [2, 3],
       [8, 0],
       [2, 9],
       [3, 5]])

In [134]:
M[1:3, 0:2] = np.array([[7,8],[1,1]])
M

array([[4, 6, 7],
       [7, 8, 3],
       [1, 1, 2],
       [9, 3, 5]])

In [132]:
M.reshape(2,-1)

array([[4, 6, 7, 7, 8, 3],
       [1, 1, 2, 9, 3, 5]])

In [136]:
M.reshape(-1,4)

array([[4, 6, 7, 7],
       [8, 3, 1, 1],
       [2, 9, 3, 5]])

In [140]:
M.reshape(-1)

array([4, 6, 7, 7, 8, 3, 1, 1, 2, 9, 3, 5])

In [142]:
M.flatten()

array([4, 6, 7, 7, 8, 3, 1, 1, 2, 9, 3, 5])

In [144]:
M.T

array([[4, 7, 1, 9],
       [6, 8, 1, 3],
       [7, 3, 2, 5]])

In [146]:
M.min()

1

In [154]:
M.min(axis = 1) #contain the min value from each row of matrix M

array([4, 3, 1, 3])

In [156]:
M.min(axis = 0) #When axis=0 is used, the function operates column-wise.

array([1, 1, 2])

In [160]:
M.sum(axis =1)

array([17, 18,  4, 17])

In [164]:
M.sum(axis = 0)

array([21, 18, 17])

In [166]:
y

array([67.  , 89.  , 45.34, 69.  , 11.  , 35.  ])

In [168]:
y.reshape(3,2)

array([[67.  , 89.  ],
       [45.34, 69.  ],
       [11.  , 35.  ]])

In [170]:
M.argmax()

9

In [172]:
M

array([[4, 6, 7],
       [7, 8, 3],
       [1, 1, 2],
       [9, 3, 5]])

In [178]:
M = M.astype(np.float16)
M

array([[4., 6., 7.],
       [7., 8., 3.],
       [1., 1., 2.],
       [9., 3., 5.]], dtype=float16)

In [180]:
x

array([78, 12, 99, 48, 71, 11, 28], dtype=int8)

In [182]:
y = x

In [184]:
x

array([78, 12, 99, 48, 71, 11, 28], dtype=int8)

In [186]:
y

array([78, 12, 99, 48, 71, 11, 28], dtype=int8)

In [188]:
y[0]=21

In [190]:
y

array([21, 12, 99, 48, 71, 11, 28], dtype=int8)

In [192]:
y[0]=20

In [194]:
y

array([20, 12, 99, 48, 71, 11, 28], dtype=int8)

In [196]:
id(x)

2137287303952

In [198]:
y = x.copy()
y

array([20, 12, 99, 48, 71, 11, 28], dtype=int8)

In [200]:
id(x)

2137287303952

In [202]:
id(y)

2137318340432