In [1]:
import numpy as np


##### Creat the array

In [2]:
x = np.array([56,12,35,48,71,11,28])

In [3]:
print(x)

[56 12 35 48 71 11 28]


In [4]:
type(x)

numpy.ndarray

In [5]:
x.ndim

1

In [6]:
x

array([56, 12, 35, 48, 71, 11, 28])

In [7]:
x.dtype

dtype('int32')

In [11]:
a= 2324324359845409583000000000000000000000000000000000004444444444444444444444444444444444444444433333333333333333333333333333333333

In [12]:
a

2324324359845409583000000000000000000000000000000000004444444444444444444444444444444444444444433333333333333333333333333333333333

In [ ]:
x=np.array

In [13]:
y=np.array([67,89,45,34,69,11,35])

In [15]:
y=np.array([67,89,45,34.68,69,11,35])

In [22]:
y=np.array([67,89,45,34.68,69,11,35,'ram'])

In [24]:
y

array(['67', '89', '45', '34.68', '69', '11', '35', 'ram'], dtype='<U32')

In [14]:
y

array([67, 89, 45, 34, 69, 11, 35])

In [16]:
y

array([67.  , 89.  , 45.  , 34.68, 69.  , 11.  , 35.  ])

In [17]:
type(y)

numpy.ndarray

In [18]:
y.dtype

dtype('float64')

In [19]:
z= np.array([67,89,45,34.68,69,11,True])

In [20]:
z

array([67.  , 89.  , 45.  , 34.68, 69.  , 11.  ,  1.  ])

In [ ]:
array

In [ ]:
array([0,0,0,0,0,0,0,0])

In [25]:
np.arange(0,10,0.33)

array([0.  , 0.33, 0.66, 0.99, 1.32, 1.65, 1.98, 2.31, 2.64, 2.97, 3.3 ,
       3.63, 3.96, 4.29, 4.62, 4.95, 5.28, 5.61, 5.94, 6.27, 6.6 , 6.93,
       7.26, 7.59, 7.92, 8.25, 8.58, 8.91, 9.24, 9.57, 9.9 ])

In [26]:
np.arange(2,20,3)

array([ 2,  5,  8, 11, 14, 17])

##### array operatio

In [35]:
num1=np.array([56, 12, 35, 48, 71, 11, 28])
num2= np.array([28,28, 19, 39, 38, 74, 20])

In [28]:
num1+10

array([66, 22, 45, 58, 81, 21, 38])

In [36]:
num1+num2

array([ 84,  40,  54,  87, 109,  85,  48])

In [37]:
num1-num2

array([ 28, -16,  16,   9,  33, -63,   8])

In [29]:
num1/10

array([5.6, 1.2, 3.5, 4.8, 7.1, 1.1, 2.8])

In [30]:
num1*5

array([280,  60, 175, 240, 355,  55, 140])

In [30]:
num1*5

array([280,  60, 175, 240, 355,  55, 140])

In [31]:
[56, 12, 35, 48, 71, 11, 28]*3

[56,
 12,
 35,
 48,
 71,
 11,
 28,
 56,
 12,
 35,
 48,
 71,
 11,
 28,
 56,
 12,
 35,
 48,
 71,
 11,
 28]

##### Matrix

In [39]:
M = np.array([[4,6,7], [1,2,3],[8,0,3],[9,3,5]])

In [41]:
M


array([[4, 6, 7],
       [1, 2, 3],
       [8, 0, 3],
       [9, 3, 5]])

In [42]:
M.dtype

dtype('int32')

In [44]:
M.size

12

In [43]:
    M.shape

(4, 3)

In [45]:
    M.ndim

2

In [46]:
M[2,1]

0

In [47]:
M.T

array([[4, 1, 8, 9],
       [6, 2, 0, 3],
       [7, 3, 3, 5]])

In [48]:
M.reshape(-1,4)

array([[4, 6, 7, 1],
       [2, 3, 8, 0],
       [3, 9, 3, 5]])

In [49]:
M.min()

0

In [50]:
M.min(axis=1)

array([4, 1, 0, 3])

In [51]:
M.min(axis=0)

array([1, 0, 3])

In [52]:
M.dtype

dtype('int32')

In [53]:
M=M.astype(np.int64)

In [53]:
M=M.astype(np.int64)

In [54]:
M

array([[4, 6, 7],
       [1, 2, 3],
       [8, 0, 3],
       [9, 3, 5]], dtype=int64)

In [57]:
x= np.array([11,12,28,35,48,71,145])

In [58]:
y=x

In [59]:
y

array([ 11,  12,  28,  35,  48,  71, 145])

In [60]:
y[0]=20

In [61]:
x

array([ 20,  12,  28,  35,  48,  71, 145])

In [62]:
id(x)

1716892283888

In [63]:
id(y)

1716892283888

In [64]:
y=x.copy()
y

array([ 20,  12,  28,  35,  48,  71, 145])

In [65]:
x

array([ 20,  12,  28,  35,  48,  71, 145])

In [66]:
y

array([ 20,  12,  28,  35,  48,  71, 145])

In [67]:
x

array([ 20,  12,  28,  35,  48,  71, 145])

In [68]:
x= np.array([11,12,28,35,48,71,145])

In [69]:
y=x.copy()

In [70]:
x

array([ 11,  12,  28,  35,  48,  71, 145])

In [71]:
y

array([ 11,  12,  28,  35,  48,  71, 145])

In [72]:
y[0]=20

In [73]:
x

array([ 11,  12,  28,  35,  48,  71, 145])

In [74]:
y

array([ 20,  12,  28,  35,  48,  71, 145])